/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type PoolKeyStruct = {
  currency0: string;
  currency1: string;
  fee: BigNumberish;
  tickSpacing: BigNumberish;
  hooks: string;
};

export type PoolKeyStructOutput = [string, string, number, number, string] & {
  currency0: string;
  currency1: string;
  fee: number;
  tickSpacing: number;
  hooks: string;
};

export interface PoolAbiInterface extends utils.Interface {
  functions: {
    "deployPoolWithHook((address,address,uint24,int24,address),uint160,bytes,bytes,bytes32)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "deployPoolWithHook"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployPoolWithHook",
    values: [PoolKeyStruct, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployPoolWithHook",
    data: BytesLike
  ): Result;

  events: {};
}

export interface PoolAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployPoolWithHook(
      key: PoolKeyStruct,
      sqrtPriceX96: BigNumberish,
      hookData: BytesLike,
      hookBytecode: BytesLike,
      hookSalt: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  deployPoolWithHook(
    key: PoolKeyStruct,
    sqrtPriceX96: BigNumberish,
    hookData: BytesLike,
    hookBytecode: BytesLike,
    hookSalt: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployPoolWithHook(
      key: PoolKeyStruct,
      sqrtPriceX96: BigNumberish,
      hookData: BytesLike,
      hookBytecode: BytesLike,
      hookSalt: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    deployPoolWithHook(
      key: PoolKeyStruct,
      sqrtPriceX96: BigNumberish,
      hookData: BytesLike,
      hookBytecode: BytesLike,
      hookSalt: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployPoolWithHook(
      key: PoolKeyStruct,
      sqrtPriceX96: BigNumberish,
      hookData: BytesLike,
      hookBytecode: BytesLike,
      hookSalt: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
