/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { L1VaultAbi, L1VaultAbiInterface } from "../L1VaultAbi";

const _abi = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [
      {
        name: "token_",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount_",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "tokenDeposits",
    inputs: [
      {
        name: "erc20Address",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenMetadata",
    inputs: [
      {
        name: "erc20Address",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "metadata",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userDeposits",
    inputs: [
      {
        name: "erc20Address",
        type: "address",
        internalType: "address",
      },
      {
        name: "user",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "error",
    name: "NoERC20Metadata",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "key",
        type: "string",
        internalType: "string",
      },
    ],
  },
  {
    type: "error",
    name: "StringIsTooLong",
    inputs: [
      {
        name: "length",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxLength",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [],
  },
] as const;

export class L1VaultAbi__factory {
  static readonly abi = _abi;
  static createInterface(): L1VaultAbiInterface {
    return new utils.Interface(_abi) as L1VaultAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): L1VaultAbi {
    return new Contract(address, _abi, signerOrProvider) as L1VaultAbi;
  }
}
